import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { PrismaClient } from '@prisma/client';
import type { AddressInfo } from 'node:net';
import { Client, type Room } from 'colyseus.js';
import { AUTHENTICATED_ROOM, type WorldRoomState } from '@mmorpg/shared';
import { AuthService } from '../src/auth.js';
import { createGameServer } from '../src/server.js';
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
async function until(predicate: () => boolean) { const end = Date.now() + 5000; while (!predicate()) { if (Date.now() > end) throw new Error('Auth state timeout'); await sleep(25); } }
export async function testAuth(database: PrismaClient) {
  const requestId = randomUUID(), username = `auth-${requestId}`, password = 'test-only-password';
  let now = Date.now(); const auth = new AuthService(database, 120000, () => now);
  const input = { requestId, username, password, class: 'TANK' };
  const [registration, retry] = await Promise.all([auth.register(input), auth.register(input)]);
  assert.deepEqual(registration, retry);
  const game = createGameServer(false, false, auth);
  try {
    const count = await database.account.count();
    await assert.rejects(auth.register({ ...input, requestId: randomUUID() }));
    assert.equal(await database.account.count(), count);
    await assert.rejects(auth.register({ ...input, password: 'wrong' }));
    await assert.rejects(auth.login({ username, password: 'wrong' }));
    await assert.rejects(auth.login({ username: 'missing', password }));
    const credential = await database.credential.findUniqueOrThrow({ where: { username } });
    assert.notEqual(credential.passwordHash, password); assert.match(credential.passwordHash, /^scrypt-v1:/);
    const concurrent = await Promise.all([auth.login({ username, password }), auth.login({ username, password })]);
    const validation = await Promise.allSettled(concurrent.map(session => auth.authenticate(session.token)));
    assert.equal(validation.filter(result => result.status === 'fulfilled').length, 1);
    const active = concurrent[validation.findIndex(result => result.status === 'fulfilled')]!;
    await game.server.listen(0, '127.0.0.1');
    const base = `http://127.0.0.1:${(game.httpServer.address() as AddressInfo).port}`, client = new Client(base);
    await assert.rejects(client.joinOrCreate(AUTHENTICATED_ROOM, { version: 1, token: '0'.repeat(64) }));
    const join = (token: string, reconnect = false) => client.joinOrCreate<WorldRoomState>(AUTHENTICATED_ROOM, { version: 1, token, reconnect });
    const first = await join(active.token); first.onLeave(() => {});
    await until(() => first.state?.players?.has(registration.characterId));
    first.send('movement', { version: 1, sequence: 0, x: 1, y: 0 });
    await until(() => first.state.players.get(registration.characterId)!.x > 624);
    first.send('movement', { version: 1, sequence: 1, x: 0, y: 0 });
    await until(() => first.state.players.get(registration.characterId)!.lastSequence === 1);
    const x = first.state.players.get(registration.characterId)!.x;
    first.connection.close(); await sleep(150);
    const restored = await join(active.token, true); restored.onLeave(() => {});
    await until(() => restored.state?.players?.has(registration.characterId));
    assert.equal(restored.state.players.size, 1); assert.equal(restored.state.players.get(registration.characterId)!.x, x);
    assert.equal(await database.character.count({ where: { accountId: registration.accountId } }), 1);
    let replaced = false; restored.onLeave(() => { replaced = true; });
    const next = await auth.login({ username, password });
    await until(() => replaced);
    await assert.rejects(auth.authenticate(active.token));
    await assert.rejects(join(active.token, true));
    const second = await join(next.token); second.onLeave(() => {});
    await until(() => second.state?.players?.size === 1);
    second.connection.close(); await sleep(150); now += 30001; await sleep(150);
    await assert.rejects(join(next.token, true));
    const third = await join(next.token); third.onLeave(() => {});
    await until(() => third.state?.players?.size === 1);
    now += 120001; await sleep(150);
    await assert.rejects(auth.authenticate(next.token));
    await assert.rejects(join(next.token));
    const response = await fetch(`${base}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) });
    assert.equal(response.status, 200);
    const session = await response.json() as { token: string };
    assert.equal(response.headers.get('cache-control'), 'no-store');
    const protectedRoom: Room<WorldRoomState> = await join(session.token); let loggedOut = false; protectedRoom.onLeave(() => { loggedOut = true; });
    const logout = await fetch(`${base}/auth/logout`, { method: 'POST', headers: { Authorization: `Bearer ${session.token}` } });
    assert.equal(logout.status, 204); await until(() => loggedOut);
    await assert.rejects(auth.authenticate(session.token));
    const recovery = await fetch(`${base}/auth/recovery`, { method: 'POST' }); assert.equal(recovery.status, 503);
    assert.deepEqual(await recovery.json(), { error: 'RECOVERY_NOT_CONFIGURED' });
    console.log('Auth: real DB registration retry/uniqueness, concurrent login, invalid credentials/token, WS movement, authenticated reconnect within grace, timeout, replacement, expiry, logout and deferred recovery passed');
  } finally {
    await game.server.gracefullyShutdown(false);
    await database.gameplaySession.deleteMany({ where: { accountId: registration.accountId } });
    await database.credential.deleteMany({ where: { accountId: registration.accountId } });
    await database.characterInitialization.deleteMany({ where: { characterId: registration.characterId } });
    await database.character.deleteMany({ where: { accountId: registration.accountId } });
    await database.account.deleteMany({ where: { id: registration.accountId } });
    await database.operationReceipt.deleteMany({ where: { scope: 'registration', key: requestId } });
  }
}
