import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type { PrismaClient } from '@prisma/client';
import { AuthService, tokenHash } from '../src/auth.js';
import { RecoveryService, type EmailMessage } from '../src/recovery.js';
import { createGameServer } from '../src/server.js';
import { Client } from 'colyseus.js';
import { AUTHENTICATED_ROOM, type WorldRoomState } from '@mmorpg/shared';
import type { AddressInfo } from 'node:net';
export async function testRecovery(database: PrismaClient) {
  let now = Date.now(); const auth = new AuthService(database, 120000, () => now), messages: EmailMessage[] = [];
  const recovery = new RecoveryService(auth, { async send(message) { messages.push(message); } }, { tokenTtlMs: 60000, cooldownMs: 1000 });
  const requestId = randomUUID(), username = `recovery-${requestId}`, password = 'test-original';
  const registered = await auth.register({ requestId, username, password, class: 'TANK' });
  const value = { email: `${requestId}@example.invalid`, password };
  const game = createGameServer(false, false, auth);
  try {
    const session = await auth.login({ username, password });
    await game.server.listen(0, '127.0.0.1');
    const client = new Client(`http://127.0.0.1:${(game.httpServer.address() as AddressInfo).port}`);
    const room = await client.joinOrCreate<WorldRoomState>(AUTHENTICATED_ROOM, { version: 1, token: session.token });
    const disconnected = new Promise<void>(resolve => room.onLeave(() => resolve()));
    await recovery.requestReset({ username }); await recovery.requestReset({ username: randomUUID() }); assert.equal(messages.length, 0);
    await assert.rejects(recovery.requestVerification('0'.repeat(64), value));
    await assert.rejects(recovery.requestVerification(session.token, { ...value, password: 'wrong' }));
    await recovery.requestVerification(session.token, value);
    const verification = messages.at(-1)!; assert.equal(verification.purpose, 'VERIFY_EMAIL');
    const stored = await database.emailChallenge.findUniqueOrThrow({ where: { tokenHash: tokenHash(verification.token) } });
    assert.notEqual(stored.tokenHash, verification.token);
    assert.equal((await database.credential.findUniqueOrThrow({ where: { username } })).emailVerifiedAt, null);
    await recovery.requestReset({ username }); assert.equal(messages.length, 1);
    await assert.rejects(recovery.resetPassword({ token: verification.token, password: 'new', confirmation: 'new' }));
    await recovery.verifyEmail({ token: verification.token }); await assert.rejects(recovery.verifyEmail({ token: verification.token }));
    await recovery.requestReset({ username }); const reset = messages.at(-1)!;
    assert.equal(reset.to, value.email); assert.equal(reset.purpose, 'RESET_PASSWORD');
    await recovery.requestReset({ username }); assert.equal(messages.length, 2);
    await assert.rejects(recovery.verifyEmail({ token: reset.token }));
    await assert.rejects(recovery.resetPassword({ token: reset.token, password: 'new', confirmation: 'different' }));
    const results = await Promise.allSettled([0, 1].map(() => recovery.resetPassword({ token: reset.token, password: 'test-new', confirmation: 'test-new' })));
    assert.equal(results.filter(r => r.status === 'fulfilled').length, 1);
    await Promise.race([disconnected, new Promise<never>((_resolve, reject) => setTimeout(() => reject(new Error('Reset did not disconnect gameplay')), 3000).unref())]);
    await assert.rejects(auth.authenticate(session.token)); await assert.rejects(auth.login({ username, password }));
    const next = await auth.login({ username, password: 'test-new' }); assert.ok(next.token);
    now += 1001; await recovery.requestReset({ username }); const expired = messages.at(-1)!; now += 60000;
    await assert.rejects(recovery.resetPassword({ token: expired.token, password: 'another', confirmation: 'another' }));
    await auth.authenticate(next.token);
    await recovery.requestReset({ username }); const oldReset = messages.at(-1)!;
    await recovery.requestVerification(next.token, { email: `changed-${value.email}`, password: 'test-new' });
    const changed = messages.at(-1)!; await recovery.verifyEmail({ token: changed.token });
    await assert.rejects(recovery.resetPassword({ token: oldReset.token, password: 'another', confirmation: 'another' }));
    now += 1001; await recovery.requestReset({ username }); assert.equal(messages.at(-1)!.to, `changed-${value.email}`);
    now += 1001;
    const failing = new RecoveryService(auth, { async send() { throw new Error('test transport failure'); } }, { tokenTtlMs: 60000, cooldownMs: 1000 });
    await assert.rejects(failing.requestReset({ username }));
    assert.equal(await database.emailChallenge.count({ where: { accountId: registered.accountId } }), 0);
    assert.equal(await database.character.count({ where: { accountId: registered.accountId } }), 1);
    console.log('Recovery: verified-only delivery, reauth, purpose binding, hashed/expiring/single-use tokens, concurrent reset, cooldown, old-email invalidation, session revocation, transport failure PASS');
  } finally {
    await game.server.gracefullyShutdown(false);
    const accountId = registered.accountId;
    await database.emailChallenge.deleteMany({ where: { accountId } });
    await database.gameplaySession.deleteMany({ where: { accountId } });
    await database.credential.deleteMany({ where: { accountId } });
    await database.characterInitialization.deleteMany({ where: { characterId: registered.characterId } });
    await database.character.deleteMany({ where: { accountId } });
    await database.account.deleteMany({ where: { id: accountId } });
    await database.operationReceipt.deleteMany({ where: { scope: 'registration', key: requestId } });
  }
}
